// @ts-nocheck
import { Field, ObjectType } from '@nestjs/graphql';
import { Entity, Index, PrimaryColumn } from 'typeorm';

//This entity is the example for the composed primary key, generated by the 2 PrimaryColumn decorators and the index.
@Index('guid', ['guid', 'role'], { unique: true })
@Entity('assignedRoles', { schema: 'boxedoutAdmin' })
@ObjectType()
export class Role {
  @Field({ name: 'userId' })
  @PrimaryColumn({ type: 'varchar', name: 'guid', length: 36 })
  guid: string;

  @PrimaryColumn({ type: 'varchar', name: 'role', length: 100 })
  role: string;
}
