sonar.exclusions=**/node_modules/**/*,**/*.spec.ts,/test/**/*.*
sonar.cpd.exclusions=libs/boxedout-libs/db-userBalance/src/entities/index.ts, libs/boxedout-libs/db-userTransactions/src/config/database.ts, libs/boxedout-libs/db-priceHistory/src/entities/index.ts, libs/boxedout-libs/db-userTransactions/src/entities/index.ts
