export enum LogActionTypeEnum {
  SKELETON_USER_CREATED = 'SkeletonUser.created',
  SKELETON_USER_UPDATED = 'SkeletonUser.updated',
  SKELETON_USER_DELETED = 'SkeletonUser.deleted',
  // Legacy types, please migrate these when you need them.
  AGENT_CHANGE_EMAIL = 'agent_change_email',
  AGENT_CHANGE_NAME = 'agent_change_name',
  AGENT_COMMENTS_POST = 'agent_comments_post',
  AGENT_DELETE_IBAN = 'agent_delete_iban',
  AGENT_DISABLE_COOLDOWN = 'agent_disable_cooldown',
  AGENT_DISABLE_TWO_FACTOR = 'agent_disable_two_factor',
  AGENT_IDENTITIES_POST = 'agent_identities_post',
  AGENT_LOCK_POST = 'agent_lock_post',
  AGENT_REMOVE_FROM_EMAIL_BLACKLIST = 'agent_remove_from_email_blacklist',
  AGENT_ADD_TAG = 'agent_add_tag',
  AGENT_UPDATE_TAG = 'agent_update_tag',
  AGENT_REMOVE_TAG = 'agent_remove_tag',
  ALL_QUEUE_POST = 'all_queue_post',
  COMPLIANCE_ADDRESSBOOK_POST = 'compliance_addressbook_post',
  COMPLIANCE_FIU_POST = 'compliance_fiu_post',
  COMPLIANCE_IBAN_POST = 'compliance_iban_post',
  COMPLIANCE_IDENTITIES_POST = 'compliance_identities_post',
  COMPLIANCE_IDENTITIES_PUT = 'compliance_identities_put',
  COMPLIANCE_LOCK_POST = 'compliance_lock_post',
  COMPLIANCE_LOCK_PUT = 'compliance_lock_put',
  COMPLIANCE_MONITOR_ACTION_POST = 'compliance_monitor_action_post',
  COMPLIANCE_MONITOR_ASSETS_POST = 'compliance_monitor_assets_post',
  COMPLIANCE_PROOF_OF_FUNDS_POST = 'compliance_proof_of_funds_post',
  COMPLIANCE_SANCTIONLIST_POST = 'compliance_sanctionlist_post',
  COMPLIANCE_TAGS_DELETE = 'compliance_tags_delete',
  COMPLIANCE_TAGS_POST = 'compliance_tags_post',
  COMPLIANCE_TRANSACTION_LIMITS_POST = 'compliance_transaction_limits_post',
  COMPLIANCE_TRANSACTION_LIMITS_PUT = 'compliance_transaction_limits_put',
  MANAGEMENT_EMAILS_POST = 'management_emails_post',
  MANAGEMENT_EMAILS_PUT = 'management_emails_put',
  MANAGEMENT_ROLES_POST = 'management_roles_post',
  MANAGEMENT_ROLES_PUT = 'management_roles_put',

  // Migrated legacy types, changed the IDs although the values should be kept to guarantee backwards compatibility
  // @todo Migrate these values to new more readable values
  USER_PHONE_UPDATED = 'agent_change_phone',

  // New types, please try to use clear values
  USER_PHONE_CREATED = 'UserPhone.created',
  USER_PHONE_DELETED = 'UserPhone.deleted',
  CORPORATE_ENTITY_CREATED = 'CorporateEntity.created',
  CORPORATE_ENTITY_UPDATED = 'CorporateEntity.updated',
  CORPORATE_ENTITY_DELETED = 'CorporateEntity.deleted',
  CORPORATE_PERSON_OF_INTEREST_CREATED = 'CorporatePersonOfInterest.created',
  CORPORATE_PERSON_OF_INTEREST_UPDATED = 'CorporatePersonOfInterest.updated',
  CORPORATE_PERSON_OF_INTEREST_DELETED = 'CorporatePersonOfInterest.deleted',
  BOXEDOUT_REWARD_RATE_CREATED = 'BoxedOutRewardRate.created',
  BOXEDOUT_REWARD_RATE_UPDATED = 'BoxedOutRewardRate.updated',
  BOXEDOUT_REWARD_RATE_DELETED = 'BoxedOutRewardRate.deleted',
  USER_UPDATED = 'User.updated',
  CUSTOM_CODE_CREATED = 'CustomCode.created',
  CUSTOM_CODE_UPDATED = 'CustomCode.updated',
  CUSTOM_CODE_DELETED = 'CustomCode.deleted',
  DEPOSIT_UPDATE = 'Deposit.update',
  USERQUESTIONNAIRE_UPDATE = 'UserQuestionnaire.updated',
  REFUND_CUSTOMER_CREATED = 'adminMetadata.refundCustomer.created',
  REFUND_CUSTOMER_UPDATED = 'adminMetadata.refundCustomer.updated',
  USER_ADDRESS_CREATED = 'UserAddress.created',
  USER_ADDRESS_UPDATED = 'UserAddress.updated',
  USER_ADDRESS_DELETED = 'UserAddress.deleted',
  USER_COMPENSATE_ADD_REQUEST = 'UserCompensate.addRequest',
  USER_COMPENSATE_UPDATE_REQUEST = 'UserCompensate.updateRequest',
  USER_FILE_DELETED = 'UserFile.deleted',
  USER_LOCK_DUPLICATE_ACCOUNT = 'User.lockDuplicate.update',
  USER_UNLOCK_DUPLICATE_ACCOUNT = 'User.unlockDuplicate.update',
  USER_HANDLE_DUPLICATE_ACCOUNT = 'User.handleDuplicateAccount.update',
  STUCK_WITHDRAWALS_ADD_REQUEST = 'CryptoWithdrawalStuck.addRequest',
  STUCK_WITHDRAWALS_UPDATE_REQUEST = 'CryptoWithdrawalStuck.updateRequest',
}
