name: App Manage-Panel Pipeline
on:
  workflow_dispatch:
    inputs:
      skipchecks:
        description: 'Skip check jobs.'
        required: false
        type: boolean
        default: false
  push:
    branches:
      - master
      - rc
      - dev
    paths:
      - '.github/actions/**'
      - '.github/workflows/app-manage-panel.yml'
      - 'apps/manage-panel/**'
      - 'libs/bitvavo/auth/**'
      - 'libs/bitvavo/manage-**'
      - 'libs/bitvavo-libs/**'
      - 'libs/common/**'
      - 'test/**'
      - 'conf/**'
      # execute when root level files change
      - '*'
  pull_request:
    branches-ignore:
      - 'master' # PRs that target master do not execute the action automatically
    paths:
      - '.github/actions/**'
      - '.github/workflows/app-manage-panel.yml'
      - 'apps/manage-panel/**'
      - 'libs/bitvavo/auth/**'
      - 'libs/bitvavo/manage-**'
      - 'libs/bitvavo-libs/**'
      - 'libs/common/**'
      - 'test/**'
      - 'conf/**'
      # execute when root level files change
      - '*'

env:
  PROJECT_ID: manage-panel
  NODE_VERSION: 22
  # AWS DEV SECRETS
  AWS_SECRET_DEV_KEY_ID: ${{ secrets.AWS_DEV_ACCESS_KEY_ID }}
  AWS_SECRET_DEV_KEY: ${{ secrets.AWS_DEV_ACCESS_KEY }}
  AWS_ACCOUNT_DEV_ID: ${{ secrets.AWS_DEV_ACCOUNT_ID }}
  # AWS RC SECRETS
  AWS_SECRET_QA_KEY_ID: ${{ secrets.AWS_RC_ACCESS_KEY_ID }}
  AWS_SECRET_QA_KEY: ${{ secrets.AWS_RC_ACCESS_KEY }}
  AWS_ACCOUNT_QA_ID: ${{ secrets.AWS_RC_ACCOUNT_ID }}
  # AWS PROD SECRETS
  AWS_SECRET_PROD_KEY_ID: ${{ secrets.AWS_PROD_ACCESS_KEY_ID }}
  AWS_SECRET_PROD_KEY: ${{ secrets.AWS_PROD_ACCESS_KEY }}
  AWS_ACCOUNT_PROD_ID: ${{ secrets.AWS_PROD_ACCOUNT_ID }}
  # other
  GITHUB_TOKEN: ${{ secrets.READ_PACKAGE_TOKEN }}
  NODE_ENV: 'pipeline'
  JWT_SECRET_PVT: 'dummydummyprivate'
  JWT_SECRET_PUB: 'dummydummypublic'
jobs:
  #===========================
  #
  #  PREPARE PIPELINE
  #
  #============================
  prepare-pipeline:
    name: Prepare Pipeline
    runs-on: ubuntu-latest
    outputs:
      github_stage: ${{ steps.bitvavo.outputs.github_stage }}
      project_id: ${{ steps.bitvavo.outputs.project_id }}
    steps:
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Cache global npm
        uses: actions/cache@v3
        env:
          cache-name: cache-${{ env.PROJECT_ID }}-global-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'
          token: ${{ secrets.PUBLISH_TOKEN }}
      - name: Cache local node_modules
        uses: actions/cache@v3
        env:
          cache-name: cache-${{ env.PROJECT_ID }}-modules
        with:
          path: 'node_modules'
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
      - name: Run Bitvavo actions
        id: bitvavo
        with:
          run-install: true
          project-id: ${{ env.PROJECT_ID }}
        uses: ./.github/actions/bitvavo-actions
      # to make sure that the bitvavo actions worked
      - name: Check npm version
        run: npm --version

  #===========================
  #
  #  RUN PARALLEL JOBS
  #
  #============================
  linter:
    if: github.event.inputs.skipchecks != 'true'
    name: Linter Checks
    needs: prepare-pipeline
    runs-on: ubuntu-latest
    steps:
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'
          token: ${{ secrets.PUBLISH_TOKEN }}
      - name: Restore node_modules cache
        uses: actions/cache@v3
        env:
          cache-name: cache-${{ env.PROJECT_ID }}-modules
        with:
          path: 'node_modules'
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
      - name: Run Bitvavo actions
        id: bitvavo
        with:
          project-id: ${{ env.PROJECT_ID }}
        uses: ./.github/actions/bitvavo-actions
      - name: Lint check
        run: npm run lint:path --lintpath=apps/${{ env.PROJECT_ID }};

  test-unit:
    if: github.event.inputs.skipchecks != 'true'
    name: Unit Tests
    needs: prepare-pipeline
    runs-on: ubuntu-latest
    steps:
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'
          token: ${{ secrets.PUBLISH_TOKEN }}
      - name: Restore node_modules cache
        uses: actions/cache@v3
        env:
          cache-name: cache-${{ env.PROJECT_ID }}-modules
        with:
          path: 'node_modules'
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
      - name: Run Bitvavo actions
        id: bitvavo
        with:
          project-id: ${{ env.PROJECT_ID }}
        uses: ./.github/actions/bitvavo-actions
      - name: Test coverage
        run: npm run test:cov -- --ci apps/${{ env.PROJECT_ID }};
      - name: Upload coverage artifacts
        if: steps.bitvavo.outputs.github_stage != 'other' # deploy only for dev, qa and prod
        uses: actions/upload-artifact@master
        with:
          name: apps-${{ env.PROJECT_ID }}
          path: docs/compodoc/jestcoverage/apps/${{ env.PROJECT_ID }}
          retention-days: 80

  dry-runs:
    name: Dry runs
    if: github.event.inputs.skipchecks != 'true'
    needs: prepare-pipeline
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis
        # Set health checks to wait until redis has started
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6379:6379
      mysql:
        image: ghcr.io/bitvavo/mysql:5.7.4
        credentials:
          username: ${{ github.actor }}
          password: ${{ secrets.READ_PACKAGE_TOKEN }}
        env:
          MYSQL_DATABASE: bitvavo
          MYSQL_ROOT_PASSWORD: 'xs2mysql'
        ports:
          - 3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'
          token: ${{ secrets.PUBLISH_TOKEN }}
      - name: Restore node_modules cache
        uses: actions/cache@v3
        env:
          cache-name: cache-${{ env.PROJECT_ID }}-modules
        with:
          path: 'node_modules'
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
      - name: Run Bitvavo actions
        id: bitvavo
        with:
          project-id: ${{ env.PROJECT_ID }}
        uses: ./.github/actions/bitvavo-actions
      - name: Build
        run: |
          npm run build
        # npm run build:bundle
      - name: Dry runs
        env:
          MYSQL_HOST: '127.0.0.1'
          MYSQL_USER: 'root'
          MYSQL_ROOT_PASSWORD: 'xs2mysql'
          MYSQL_PORT: ${{ job.services.mysql.ports['3306'] }}
          REDIS_HOST: localhost
          REDIS_PORT: 6379
          AUTH0_JWKS_URI: https://dev-bitvavo.eu.auth0.com/.well-known/jwks.json
          AUTH0_ISSUER: https://login.dev.vavo.dev/
          AUTH0_AUDIENCE: https://api.dev.vavo.dev
        run: |
          npm run typeorm:initdb;
          APP_DRY_RUN=1 npm run start:prod;
          cd apps/${{ env.PROJECT_ID }};
      # TODO: code used for serverless, to remove
      # npm run sls:install:deps
      # APP_DRY_RUN=1 npm run sls:lambda:index;
      # cd ../../;
      # - name: Upload build artifacts
      #   if: steps.bitvavo.outputs.github_stage != 'other' # deploy only for dev, qa and prod
      #   uses: actions/upload-artifact@master
      #   with:
      #     name: build-${{ env.PROJECT_ID }}
      #     path: env/dist/apps/${{ env.PROJECT_ID }}/bundle
      #     retention-days: 80

  test-e2e:
    if: github.event.inputs.skipchecks != 'true'
    name: Test E2E
    needs: prepare-pipeline
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis
        # Set health checks to wait until redis has started
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6379:6379
      mysql:
        image: ghcr.io/bitvavo/mysql:5.7.4
        credentials:
          username: ${{ github.actor }}
          password: ${{ secrets.READ_PACKAGE_TOKEN }}
        env:
          MYSQL_DATABASE: bitvavo
          MYSQL_ROOT_PASSWORD: 'xs2mysql'
        ports:
          - 3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'
          token: ${{ secrets.PUBLISH_TOKEN }}
      - name: Restore node_modules cache
        uses: actions/cache@v3
        env:
          cache-name: cache-${{ env.PROJECT_ID }}-modules
        with:
          path: 'node_modules'
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
      - name: Run Bitvavo actions
        id: bitvavo
        with:
          project-id: ${{ env.PROJECT_ID }}
        uses: ./.github/actions/bitvavo-actions
      - name: Test E2E
        env:
          MYSQL_HOST: '127.0.0.1'
          MYSQL_USER: 'root'
          MYSQL_ROOT_PASSWORD: 'xs2mysql'
          MYSQL_PORT: ${{ job.services.mysql.ports['3306'] }}
          REDIS_ENABLED: true
          REDIS_HOST: localhost
          REDIS_PORT: 6379
          NODE_OPTIONS: '--max-old-space-size=5120'
          AUTH0_JWKS_URI: https://dev-bitvavo.eu.auth0.com/.well-known/jwks.json
          AUTH0_ISSUER: https://login.dev.vavo.dev/
          AUTH0_AUDIENCE: https://api.dev.vavo.dev
        run: |
          npm run typeorm:initdb;
          npm run test:e2e -- --ci;

  image-creation:
    env:
      DOCKER_BUILDKIT: 1
    name: Image creation
    needs: prepare-pipeline
    runs-on: ubuntu-latest
    steps:
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'
          token: ${{ secrets.PUBLISH_TOKEN }}
      - name: Run Bitvavo actions
        id: bitvavo
        with:
          project-id: ${{ env.PROJECT_ID }}
        uses: ./.github/actions/bitvavo-actions
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.PUBLISH_TOKEN }}
      - name: Pull image for cache
        env:
          IMAGE_TAG: ${{ env.PROJECT_ID }}-latest
        run: docker pull ghcr.io/bitvavo/backend-core-api/${{ env.PROJECT_ID }}:dev-latest|| true
      - name: Build image for Github
        env:
          IMAGE_TAG_VERSION: ${{ env.CORE_API_VERSION}}
          IMAGE_TAG_LATEST: ${{ steps.bitvavo.outputs.github_branch_id }}-latest
        run: |
          docker build \
            --build-arg BUILDKIT_INLINE_CACHE=1 \
            --build-arg DOCKER_ENV=${{ env.DOCKER_ENV}} \
            --build-arg GITHUB_TOKEN=${{ secrets.PUBLISH_TOKEN }} \
            --build-arg APP_ID=${{ env.PROJECT_ID }} \
            --build-arg COMMIT_SHA=${{ env.COMMIT_SHA }} \
            --cache-from=ghcr.io/bitvavo/backend-core-api/${{ env.PROJECT_ID }}:dev-latest \
            --target distribution \
            -t ghcr.io/bitvavo/backend-core-api/${{ env.PROJECT_ID }}:${{ env.IMAGE_TAG_LATEST }} \
            -t ghcr.io/bitvavo/backend-core-api/${{ env.PROJECT_ID }}:${{ env.IMAGE_TAG_VERSION }} .

      - name: Deploy image to Github
        env:
          IMAGE_TAG: ${{ env.PROJECT_ID }}-latest
        if: steps.bitvavo.outputs.github_stage != 'other' # deploy only for dev, qa and prod
        run: |
          docker push --all-tags ghcr.io/bitvavo/backend-core-api/${{ env.PROJECT_ID }}

  #===========================
  #
  #  DEPLOY STAGE
  #
  #============================

  #
  # TODO: code used for serverless, to remove
  #
  # deploy:
  #   name: Deploy app
  #   needs: [prepare-pipeline, test-e2e, test-unit, linter, dry-runs]
  #   concurrency: ci-${{ github.workflow }}-deploy-${{ github.ref }}
  #   # deploy only for dev, qa and prod
  #   # verbose condition needed because of this limitation: https://github.com/actions/runner/issues/491#issuecomment-850884422
  #   # also, the wildcard can't work in this case because we can have 1 on success and the other on skipped
  #   if: |
  #     always() &&
  #     (needs.prepare-pipeline.result == 'success') &&
  #     (needs.test-e2e.result == 'success' || needs.test-e2e.result == 'skipped') &&
  #     (needs.test-unit.result == 'success' || needs.test-unit.result == 'skipped') &&
  #     (needs.linter.result == 'success' || needs.linter.result == 'skipped') &&
  #     (needs.dry-runs.result == 'success' || needs.dry-runs.result == 'skipped') &&
  #     contains('
  #     refs/heads/dev
  #     refs/heads/master
  #     refs/heads/rc
  #     ', github.ref)
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Use Node.js
  #       uses: actions/setup-node@v1
  #       with:
  #         node-version: ${{ env.NODE_VERSION }}
  #     - name: Checkout
  #       uses: actions/checkout@v2
  #       with:
  #         submodules: 'recursive'
  #         token: ${{ secrets.PUBLISH_TOKEN }}
  #     - name: Download build artifacts
  #       uses: actions/download-artifact@master
  #       with:
  #         name: build-${{ env.PROJECT_ID }}
  #         path: env/dist/apps/${{ env.PROJECT_ID }}/bundle
  #     - name: Run Bitvavo actions
  #       id: bitvavo
  #       with:
  #         project-id: ${{ env.PROJECT_ID }}
  #       uses: ./.github/actions/bitvavo-actions
  #     - name: Configure AWS credentials
  #       uses: aws-actions/configure-aws-credentials@v1.5.5
  #       with:
  #         aws-access-key-id: ${{ env.AWS_SECRET_KEY_ID }}
  #         aws-secret-access-key: ${{ env.AWS_SECRET_KEY }}
  #         aws-region: ${{ env.AWS_REGION }}
  #     - name: Deploy to SLS 🚀
  #       env:
  #         AWS_ACCESS_KEY_ID: ${{ env.AWS_SECRET_KEY_ID }}
  #         AWS_SECRET_ACCESS_KEY: ${{ env.AWS_SECRET_KEY }}
  #         NODE_ENV: ${{ env.DOCKER_ENV}}
  #       run: |
  #         cd apps/${{ env.PROJECT_ID }};
  #         npm run sls:deploy

  k8s-deploy:
    name: Deploy app on k8s
    needs:
      [prepare-pipeline, test-e2e, test-unit, linter, dry-runs, image-creation]
    concurrency: ci-${{ github.workflow }}-deploy-${{ github.ref }}
    # deploy only for dev, qa and prod
    # verbose condition needed because of this limitation: https://github.com/actions/runner/issues/491#issuecomment-850884422
    # also, the wildcard can't work in this case because we can have 1 on success and the other on skipped
    if: |
      always() &&
      (needs.prepare-pipeline.result == 'success') &&
      (needs.test-e2e.result == 'success' || needs.test-e2e.result == 'skipped') &&
      (needs.test-unit.result == 'success' || needs.test-unit.result == 'skipped') &&
      (needs.linter.result == 'success' || needs.linter.result == 'skipped') &&
      (needs.dry-runs.result == 'success' || needs.dry-runs.result == 'skipped') &&
      (needs.image-creation.result == 'success' || needs.image-creation.result == 'skipped') &&
      contains('
      refs/heads/dev
      refs/heads/master
      refs/heads/rc
      ', github.ref)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'
          token: ${{ secrets.PUBLISH_TOKEN }}
      - name: Deploy on k8s
        with:
          k8s_config_token: ${{ secrets.K8S_CONFIG_TOKEN }}
        uses: ./.github/actions/bitvavo-actions/k8s-deploy
